WaveShaper Oversampling
LabSound/LabSound pull request #192
Opened 2023-04-12 20:03 UTC by dug9

2x, 4x oversampling implemented from webkit, not tested vs web and doesn't sound much different with / without oversampling

2023-04-12 20:38 UTC, meshula requested changes
> doesn't sound much different 

It's good to have an implementation though, so thanks for that. I wonder if there's a use case that demonstrates it in more perceptible way?

There's a couple of small tweaks necessary to get linux/apple compiling (in the notes)

2023-04-12 20:38 UTC, meshula commented on examples/src/Examples.hpp
> +    float deg = (float) std::_Pi / 180.0f;
is std::_Pi MSVC specific? Maybe we are stuck with M_PI here for cross platform-ness?

2023-04-12 20:38 UTC, meshula commented on src/internal/src/DirectConvolver.cpp
> +//#endif
```suggestion
#if OS(DARWIN)
#include <Accelerate/Accelerate.h>
#endif
```
to compile on mac/ios we'll need this

2023-04-12 21:04 UTC, dug9 commented
Fixed.

2023-04-13 20:56 UTC, meshula commented on src/internal/src/DirectConvolver.cpp
> +#if OS(DARWIN)
```suggestion
#if defined(__APPLE__)
```

2023-04-13 20:56 UTC, meshula commented on src/internal/src/DirectConvolver.cpp
> +#if defined(__APPLE__)
#if defined(LABSOUND_PLATFORM_OSX)

2023-04-13 21:29 UTC, meshula approved these changes

2023-04-13 21:29 UTC, meshula commented
All platforms are passing! Thanks :)

2023-04-13 21:30 UTC, merged